### ISSUE TITLE
Unexpected execptions are ignored

### ISSUE THREAD

**Issue by rianquinn** [boost-experimental/ut#92] opened 2019-11-02 14:57 UTC
## Expected Behavior
If this executes:
```
"unexcepted throw"_test = [] {
    throw std::runtime_error("unexpected");
};
```

I would expect that the test would fail. 

## Actual Behavior
The test doesn't fail, and silently passed. All of the rest of the expect() in that test are ignored. 

## Steps to Reproduce the Problem

  1. Run the above code

## Specifications

  - Version: master
  - Platform: Fedora 31
  - Subsystem: ???

**Comment by krzysztof-jusiak** [comment] 2019-11-02 15:01
hmm, can't repro this one :thinking: 

```
Running "unexcepted throw"...
  Unexpected exception!
FAILED
```

https://godbolt.org/z/r2PWAF

**Comment by krzysztof-jusiak** [comment] 2019-11-02 19:41
Closing it, for now, @rianquinn as I'm not able to reproduce it, @rianquinn feel free to reopen if it's still an issue :+1: thanks

**Closed by krzysztof-jusiak** 2019-11-02 19:41 UTC

**Comment by rianquinn** [comment] 2019-11-05 21:52
I haven't been able to repro this either. It did happen though... if I see it again I will report back. For now, it is working fine.
